In [1]:
import pandas as pd
from pathlib import Path

RAW = Path("../data/raw/ttc-subway-delay-data")   # adjust if your notebook is elsewhere
files = sorted(RAW.glob("*"))
for f in files:
    print(f.name)

code-descriptions.csv
ttc-subway-delay-2020.xlsx
ttc-subway-delay-2021.xlsx
ttc-subway-delay-2022.xlsx
ttc-subway-delay-2023.xlsx
ttc-subway-delay-2024.xlsx
ttc-subway-delay-codes.xlsx
ttc-subway-delay-data-2018.xlsx
ttc-subway-delay-data-2019.xlsx
ttc-subway-delay-data-since-2025.csv
ttc-subway-delay-jan-2014-april-2017.xlsx
ttc-subway-delay-may-december-2017.xlsx
ttc-subway-delay-readme.xlsx

In [2]:
# Cell 2: the new CSV
new = pd.read_csv(RAW / "ttc-subway-delay-data-since-2025.csv")
print(new.dtypes)
new.head()

_id          int64
Date           str
Time           str
Day            str
Station        str
Code           str
Min Delay    int64
Min Gap      int64
Bound          str
Line           str
Vehicle      int64
dtype: object

,_id,Date,Time,Day,Station,Code,Min Delay,Min Gap,Bound,Line,Vehicle
0,1,2025-01-01,02:10,Wednesday,BATHURST STATION,MUSAN,5,9,E,BD,5227
1,2,2025-01-01,02:30,Wednesday,DUNDAS STATION,MUIRS,0,0,NaN,YU,0
2,3,2025-01-01,02:32,Wednesday,BROADVIEW STATION,PUMST,0,0,E,BD,0
3,4,2025-01-01,02:58,Wednesday,KEELE STATION,EUSC,0,0,W,BD,5293
4,5,2025-01-01,02:58,Wednesday,COXWELL STATION,SUAE,0,0,NaN,BD,0

In [3]:
# Cell 3: every Excel file, every sheet — columns, types, row count
for f in files:
    if f.suffix != ".xlsx" or "delay-data" not in f.name and "jan-2014" not in f.name and "may-december" not in f.name:
        continue
    sheets = pd.read_excel(f, sheet_name=None)   # None = read ALL sheets
    for sheet_name, df in sheets.items():
        print(f"{f.name} | sheet: {sheet_name} | rows: {len(df)}")
        print("   columns:", list(df.columns))
        print("   types:  ", dict(df.dtypes.astype(str)))

ttc-subway-delay-data-2018.xlsx | sheet: Jan18 | rows: 1873
   columns: ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
   types:   {'Date': 'datetime64[us]', 'Time': 'str', 'Day': 'str', 'Station': 'str', 'Code': 'str', 'Min Delay': 'int64', 'Min Gap': 'int64', 'Bound': 'str', 'Line': 'str', 'Vehicle': 'int64'}
ttc-subway-delay-data-2018.xlsx | sheet: Feb18 | rows: 1470
   columns: ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
   types:   {'Date': 'datetime64[us]', 'Time': 'str', 'Day': 'str', 'Station': 'str', 'Code': 'str', 'Min Delay': 'int64', 'Min Gap': 'int64', 'Bound': 'str', 'Line': 'str', 'Vehicle': 'int64'}
ttc-subway-delay-data-2018.xlsx | sheet: March 2018 | rows: 1621
   columns: ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
   types:   {'Date': 'datetime64[us]', 'Time': 'str', 'Day': 'str', 'Station': 'str', 'Code': 'str', 'Min Delay': 'int64', 'Min Gap': 'int64', 'Bound': 'str', 'Line': 'str', 'Vehicle': 'int64'}
ttc-subway-delay-data-2018.xlsx | sheet: April 2018 | rows: 1597
   columns: ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
   types:   {'Date': 'datetime64[us]', 'Time': 'str', 'Day': 'str', 'Station': 'str', 'Code': 'str', 'Min Delay': 'int64', 'Min Gap': 'int64', 'Bound': 'str', 'Line': 'str', 'Vehicle': 'int64'}
ttc-subway-delay-data-2018.xlsx | sheet: May 2018 | rows: 1761
   columns: ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
   types:   {'Date': 'datetime64[us]', 'Time': 'str', 'Day': 'str', 'Station': 'str', 'Code': 'str', 'Min Delay': 'int64', 'Min Gap': 'int64', 'Bound': 'str', 'Line': 'str', 'Vehicle': 'int64'}
ttc-subway-delay-data-2018.xlsx | sheet: June 2018 | rows: 1794
   columns: ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
   types:   {'Date': 'datetime64[us]', 'Time': 'str', 'Day': 'str', 'Station': 'str', 'Code': 'str', 'Min Delay': 'int64', 'Min Gap': 'int64', 'Bound': 'str', 'Line': 'str', 'Vehicle': 'int64'}
ttc-subway-delay-data-2018.xlsx | sheet: July 18 | rows: 1885
   columns: ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
   types:   {'Date': 'datetime64[us]', 'Time': 'str', 'Day': 'str', 'Station': 'str', 'Code': 'str', 'Min Delay': 'int64', 'Min Gap': 'int64', 'Bound': 'str', 'Line': 'str', 'Vehicle': 'int64'}
ttc-subway-delay-data-2018.xlsx | sheet: August 18 | rows: 1937
   columns: ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
   types:   {'Date': 'datetime64[us]', 'Time': 'str', 'Day': 'str', 'Station': 'str', 'Code': 'str', 'Min Delay': 'int64', 'Min Gap': 'int64', 'Bound': 'str', 'Line': 'str', 'Vehicle': 'int64'}
ttc-subway-delay-data-2018.xlsx | sheet: Sept 18 | rows: 1794
   columns: ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
   types:   {'Date': 'datetime64[us]', 'Time': 'str', 'Day': 'str', 'Station': 'str', 'Code': 'str', 'Min Delay': 'int64', 'Min Gap': 'int64', 'Bound': 'str', 'Line': 'str', 'Vehicle': 'int64'}
ttc-subway-delay-data-2018.xlsx | sheet: Oct 18 | rows: 1802
   columns: ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
   types:   {'Date': 'datetime64[us]', 'Time': 'str', 'Day': 'str', 'Station': 'str', 'Code': 'str', 'Min Delay': 'int64', 'Min Gap': 'int64', 'Bound': 'str', 'Line': 'str', 'Vehicle': 'int64'}
ttc-subway-delay-data-2018.xlsx | sheet: Nov 2018 | rows: 1738
   columns: ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
   types:   {'Date': 'datetime64[us]', 'Time': 'str', 'Day': 'str', 'Station': 'str', 'Code': 'str', 'Min Delay': 'int64', 'Min Gap': 'int64', 'Bound': 'str', 'Line': 'str', 'Vehicle': 'int64'}
ttc-subway-delay-data-2018.xlsx | sheet: Dec 2018 | rows: 1465
   columns: ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
   types:   {'Date': 'datetime64[us]', 'Time': 'str', 'Day': 'str', 'Station': 'str', 'Code': 'str', 'Min Delay': 'int64', 'Min Gap': 'int64', 'Bound': 'str', 'Line': 'str', 'Vehicle': 'int64'}
ttc-subway-delay-data-2019.xlsx | sheet: Jan 19 | rows: 1871
   columns: ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
   types:   {'Date': 'datetime64[us]', 'Time': 'str', 'Day': 'str', 'Station': 'str', 'Code': 'str', 'Min Delay': 'int64', 'Min Gap': 'int64', 'Bound': 'str', 'Line': 'str', 'Vehicle': 'int64'}
ttc-subway-delay-data-2019.xlsx | sheet: Feb 19 | rows: 1598
   columns: ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
   types:   {'Date': 'datetime64[us]', 'Time': 'str', 'Day': 'str', 'Station': 'str', 'Code': 'str', 'Min Delay': 'int64', 'Min Gap': 'int64', 'Bound': 'str', 'Line': 'str', 'Vehicle': 'int64'}
ttc-subway-delay-data-2019.xlsx | sheet: Mar 19 | rows: 1503
   columns: ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
   types:   {'Date': 'datetime64[us]', 'Time': 'str', 'Day': 'str', 'Station': 'str', 'Code': 'str', 'Min Delay': 'int64', 'Min Gap': 'int64', 'Bound': 'str', 'Line': 'str', 'Vehicle': 'int64'}
ttc-subway-delay-data-2019.xlsx | sheet: Apr 19 | rows: 1550
   columns: ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
   types:   {'Date': 'datetime64[us]', 'Time': 'str', 'Day': 'str', 'Station': 'str', 'Code': 'str', 'Min Delay': 'int64', 'Min Gap': 'int64', 'Bound': 'str', 'Line': 'str', 'Vehicle': 'int64'}
ttc-subway-delay-data-2019.xlsx | sheet: May 19 | rows: 1705
   columns: ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
   types:   {'Date': 'datetime64[us]', 'Time': 'str', 'Day': 'str', 'Station': 'str', 'Code': 'str', 'Min Delay': 'int64', 'Min Gap': 'int64', 'Bound': 'str', 'Line': 'str', 'Vehicle': 'int64'}
ttc-subway-delay-data-2019.xlsx | sheet: June 19 | rows: 1604
   columns: ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
   types:   {'Date': 'datetime64[us]', 'Time': 'str', 'Day': 'str', 'Station': 'str', 'Code': 'str', 'Min Delay': 'int64', 'Min Gap': 'int64', 'Bound': 'str', 'Line': 'str', 'Vehicle': 'int64'}
ttc-subway-delay-data-2019.xlsx | sheet: July 19 | rows: 1696
   columns: ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
   types:   {'Date': 'datetime64[us]', 'Time': 'str', 'Day': 'str', 'Station': 'str', 'Code': 'str', 'Min Delay': 'int64', 'Min Gap': 'int64', 'Bound': 'str', 'Line': 'str', 'Vehicle': 'int64'}
ttc-subway-delay-data-2019.xlsx | sheet: August 19 | rows: 1630
   columns: ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
   types:   {'Date': 'datetime64[us]', 'Time': 'str', 'Day': 'str', 'Station': 'str', 'Code': 'str', 'Min Delay': 'int64', 'Min Gap': 'int64', 'Bound': 'str', 'Line': 'str', 'Vehicle': 'int64'}
ttc-subway-delay-data-2019.xlsx | sheet: September 19 | rows: 1531
   columns: ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
   types:   {'Date': 'datetime64[us]', 'Time': 'str', 'Day': 'str', 'Station': 'str', 'Code': 'str', 'Min Delay': 'int64', 'Min Gap': 'int64', 'Bound': 'str', 'Line': 'str', 'Vehicle': 'int64'}
ttc-subway-delay-data-2019.xlsx | sheet: Oct 19 | rows: 1497
   columns: ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
   types:   {'Date': 'datetime64[us]', 'Time': 'str', 'Day': 'str', 'Station': 'str', 'Code': 'str', 'Min Delay': 'int64', 'Min Gap': 'int64', 'Bound': 'str', 'Line': 'str', 'Vehicle': 'int64'}
ttc-subway-delay-data-2019.xlsx | sheet: Nov 19 | rows: 1463
   columns: ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
   types:   {'Date': 'datetime64[us]', 'Time': 'str', 'Day': 'str', 'Station': 'str', 'Code': 'str', 'Min Delay': 'int64', 'Min Gap': 'int64', 'Bound': 'str', 'Line': 'str', 'Vehicle': 'int64'}
ttc-subway-delay-data-2019.xlsx | sheet: December 19 | rows: 1574
   columns: ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
   types:   {'Date': 'datetime64[us]', 'Time': 'str', 'Day': 'str', 'Station': 'str', 'Code': 'str', 'Min Delay': 'int64', 'Min Gap': 'int64', 'Bound': 'str', 'Line': 'str', 'Vehicle': 'int64'}
ttc-subway-delay-jan-2014-april-2017.xlsx | sheet: Incidents | rows: 69016
   columns: ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
   types:   {'Date': 'datetime64[us]', 'Time': 'str', 'Day': 'str', 'Station': 'str', 'Code': 'str', 'Min Delay': 'int64', 'Min Gap': 'int64', 'Bound': 'str', 'Line': 'str', 'Vehicle': 'int64'}
ttc-subway-delay-may-december-2017.xlsx | sheet: May17 | rows: 1634
   columns: ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
   types:   {'Date': 'datetime64[us]', 'Time': 'str', 'Day': 'str', 'Station': 'str', 'Code': 'str', 'Min Delay': 'int64', 'Min Gap': 'int64', 'Bound': 'str', 'Line': 'str', 'Vehicle': 'int64'}
ttc-subway-delay-may-december-2017.xlsx | sheet: June17 | rows: 1568
   columns: ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
   types:   {'Date': 'datetime64[us]', 'Time': 'str', 'Day': 'str', 'Station': 'str', 'Code': 'str', 'Min Delay': 'int64', 'Min Gap': 'int64', 'Bound': 'str', 'Line': 'str', 'Vehicle': 'int64'}
ttc-subway-delay-may-december-2017.xlsx | sheet: July 2017 | rows: 1497
   columns: ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
   types:   {'Date': 'datetime64[us]', 'Time': 'str', 'Day': 'str', 'Station': 'str', 'Code': 'str', 'Min Delay': 'int64', 'Min Gap': 'int64', 'Bound': 'str', 'Line': 'str', 'Vehicle': 'int64'}
ttc-subway-delay-may-december-2017.xlsx | sheet: August 2017 | rows: 1581
   columns: ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
   types:   {'Date': 'datetime64[us]', 'Time': 'str', 'Day': 'str', 'Station': 'str', 'Code': 'str', 'Min Delay': 'int64', 'Min Gap': 'int64', 'Bound': 'str', 'Line': 'str', 'Vehicle': 'int64'}
ttc-subway-delay-may-december-2017.xlsx | sheet: September 2017 | rows: 1478
   columns: ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
   types:   {'Date': 'datetime64[us]', 'Time': 'str', 'Day': 'str', 'Station': 'str', 'Code': 'str', 'Min Delay': 'int64', 'Min Gap': 'int64', 'Bound': 'str', 'Line': 'str', 'Vehicle': 'int64'}
ttc-subway-delay-may-december-2017.xlsx | sheet: October 2017 | rows: 1605
   columns: ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
   types:   {'Date': 'datetime64[us]', 'Time': 'str', 'Day': 'str', 'Station': 'str', 'Code': 'str', 'Min Delay': 'int64', 'Min Gap': 'int64', 'Bound': 'str', 'Line': 'str', 'Vehicle': 'int64'}
ttc-subway-delay-may-december-2017.xlsx | sheet: November 2017 | rows: 1685
   columns: ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
   types:   {'Date': 'datetime64[us]', 'Time': 'str', 'Day': 'str', 'Station': 'str', 'Code': 'str', 'Min Delay': 'int64', 'Min Gap': 'int64', 'Bound': 'str', 'Line': 'str', 'Vehicle': 'int64'}
ttc-subway-delay-may-december-2017.xlsx | sheet: Dec17 | rows: 1881
   columns: ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
   types:   {'Date': 'datetime64[us]', 'Time': 'str', 'Day': 'str', 'Station': 'str', 'Code': 'str', 'Min Delay': 'int64', 'Min Gap': 'int64', 'Bound': 'str', 'Line': 'str', 'Vehicle': 'int64'}

In [4]:
# Cell 4: look at the values inside columns (one file at a time)
old = pd.read_excel(RAW / "ttc-subway-delay-data-2019.xlsx")
print(old["Line"].value_counts())
print(old["Bound"].value_counts())
old.head()

Line
BD         898
YU         824
SRT         61
SHP         44
YU/BD       30
YUS          3
B/D          1
BD LINE      1
999          1
YU/ BD       1
Name: count, dtype: int64
Bound
E    400
S    383
W    356
N    324
B      2
Name: count, dtype: int64

,Date,Time,Day,Station,Code,Min Delay,Min Gap,Bound,Line,Vehicle
0,2019-01-01,01:08,Tuesday,YORK MILLS STATION,PUSI,0,0,S,YU,5766
1,2019-01-01,02:14,Tuesday,ST ANDREW STATION,PUMST,0,0,NaN,YU,0
2,2019-01-01,02:16,Tuesday,JANE STATION,TUSC,0,0,W,BD,5117
3,2019-01-01,02:27,Tuesday,BLOOR STATION,SUO,0,0,N,YU,5436
4,2019-01-01,03:03,Tuesday,DUPONT STATION,MUATC,11,16,N,YU,6061